ALTER TABLE IF EXISTS staging.pas_patient
    ADD COLUMN IF NOT EXISTS person_id VARCHAR,
    ADD COLUMN IF NOT EXISTS title VARCHAR,
    ADD COLUMN IF NOT EXISTS date_of_birth VARCHAR,
    ADD COLUMN IF NOT EXISTS date_of_death VARCHAR,
    ADD COLUMN IF NOT EXISTS gender_identity VARCHAR,
    ADD COLUMN IF NOT EXISTS address_line_1 VARCHAR,
    ADD COLUMN IF NOT EXISTS address_line_2 VARCHAR,
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR,
    ADD COLUMN IF NOT EXISTS registered_gp VARCHAR,
    ADD COLUMN IF NOT EXISTS next_of_kin_name VARCHAR,
    ADD COLUMN IF NOT EXISTS next_of_kin_number VARCHAR,
    ADD COLUMN IF NOT EXISTS source_system_name VARCHAR,
    ADD COLUMN IF NOT EXISTS last_refreshed_at_source_timestamp VARCHAR;

ALTER TABLE IF EXISTS staging.somerset_pathway
    ADD COLUMN IF NOT EXISTS pathway_id VARCHAR,
    ADD COLUMN IF NOT EXISTS person_id VARCHAR,
    ADD COLUMN IF NOT EXISTS patient_nhs_number VARCHAR,
    ADD COLUMN IF NOT EXISTS first_name VARCHAR,
    ADD COLUMN IF NOT EXISTS surname VARCHAR,
    ADD COLUMN IF NOT EXISTS date_of_birth VARCHAR,
    ADD COLUMN IF NOT EXISTS pathway_start_date VARCHAR,
    ADD COLUMN IF NOT EXISTS referral_route VARCHAR,
    ADD COLUMN IF NOT EXISTS referral_source VARCHAR,
    ADD COLUMN IF NOT EXISTS original_start_date VARCHAR,
    ADD COLUMN IF NOT EXISTS adjusted_start_date VARCHAR,
    ADD COLUMN IF NOT EXISTS first_seen_date VARCHAR,
    ADD COLUMN IF NOT EXISTS decision_to_treat_date VARCHAR,
    ADD COLUMN IF NOT EXISTS first_treatment_date VARCHAR,
    ADD COLUMN IF NOT EXISTS treatment_start_date VARCHAR,
    ADD COLUMN IF NOT EXISTS closed_date VARCHAR,
    ADD COLUMN IF NOT EXISTS diagnosis VARCHAR,
    ADD COLUMN IF NOT EXISTS diagnosis_icd_10 VARCHAR,
    ADD COLUMN IF NOT EXISTS is_benign VARCHAR,
    ADD COLUMN IF NOT EXISTS hospital_site_id VARCHAR,
    ADD COLUMN IF NOT EXISTS hospital_site_name VARCHAR,
    ADD COLUMN IF NOT EXISTS source_system_name VARCHAR,
    ADD COLUMN IF NOT EXISTS last_refreshed_at_source_timestamp VARCHAR;

ALTER TABLE IF EXISTS staging.pathology_hl7
    ADD COLUMN IF NOT EXISTS patient_nhs_number VARCHAR,
    ADD COLUMN IF NOT EXISTS person_id VARCHAR,
    ADD COLUMN IF NOT EXISTS pathway_id VARCHAR,
    ADD COLUMN IF NOT EXISTS result_id VARCHAR,
    ADD COLUMN IF NOT EXISTS test_name VARCHAR,
    ADD COLUMN IF NOT EXISTS result_text VARCHAR,
    ADD COLUMN IF NOT EXISTS result_value VARCHAR,
    ADD COLUMN IF NOT EXISTS unit VARCHAR,
    ADD COLUMN IF NOT EXISTS observed_at VARCHAR,
    ADD COLUMN IF NOT EXISTS reported_at VARCHAR,
    ADD COLUMN IF NOT EXISTS source_system_name VARCHAR,
    ADD COLUMN IF NOT EXISTS last_refreshed_at_source_timestamp VARCHAR;

ALTER TABLE IF EXISTS staging.radiology_hl7
    ADD COLUMN IF NOT EXISTS patient_nhs_number VARCHAR,
    ADD COLUMN IF NOT EXISTS person_id VARCHAR,
    ADD COLUMN IF NOT EXISTS pathway_id VARCHAR,
    ADD COLUMN IF NOT EXISTS result_id VARCHAR,
    ADD COLUMN IF NOT EXISTS exam_type VARCHAR,
    ADD COLUMN IF NOT EXISTS observed_at VARCHAR,
    ADD COLUMN IF NOT EXISTS reported_at VARCHAR,
    ADD COLUMN IF NOT EXISTS modality VARCHAR,
    ADD COLUMN IF NOT EXISTS priority VARCHAR,
    ADD COLUMN IF NOT EXISTS scheduled_date VARCHAR,
    ADD COLUMN IF NOT EXISTS attendance_date VARCHAR,
    ADD COLUMN IF NOT EXISTS exam_status VARCHAR,
    ADD COLUMN IF NOT EXISTS source_system_name VARCHAR,
    ADD COLUMN IF NOT EXISTS last_refreshed_at_source_timestamp VARCHAR;

ALTER TABLE IF EXISTS staging.sact_treatment
    ADD COLUMN IF NOT EXISTS person_id VARCHAR,
    ADD COLUMN IF NOT EXISTS pathway_id VARCHAR,
    ADD COLUMN IF NOT EXISTS course_id VARCHAR,
    ADD COLUMN IF NOT EXISTS scheduled_date VARCHAR,
    ADD COLUMN IF NOT EXISTS attendance_date VARCHAR,
    ADD COLUMN IF NOT EXISTS attendance_id VARCHAR,
    ADD COLUMN IF NOT EXISTS status VARCHAR,
    ADD COLUMN IF NOT EXISTS prescription_status VARCHAR,
    ADD COLUMN IF NOT EXISTS is_prescription_prepared VARCHAR,
    ADD COLUMN IF NOT EXISTS source_system_name VARCHAR,
    ADD COLUMN IF NOT EXISTS last_refreshed_at_source_timestamp VARCHAR;

ALTER TABLE IF EXISTS staging.mdt_source
    ADD COLUMN IF NOT EXISTS record_type VARCHAR,
    ADD COLUMN IF NOT EXISTS mdt_note_id VARCHAR,
    ADD COLUMN IF NOT EXISTS mdt_booking_id VARCHAR,
    ADD COLUMN IF NOT EXISTS pathway_id VARCHAR,
    ADD COLUMN IF NOT EXISTS patient_nhs_number VARCHAR,
    ADD COLUMN IF NOT EXISTS patient_name VARCHAR,
    ADD COLUMN IF NOT EXISTS patient_mrn VARCHAR,
    ADD COLUMN IF NOT EXISTS patient_person_id VARCHAR,
    ADD COLUMN IF NOT EXISTS last_updated_timestamp VARCHAR,
    ADD COLUMN IF NOT EXISTS source_system_name VARCHAR,
    ADD COLUMN IF NOT EXISTS last_refreshed_at_source_timestamp VARCHAR;

ALTER TABLE IF EXISTS staging.endoscopy_source
    ADD COLUMN IF NOT EXISTS person_id VARCHAR,
    ADD COLUMN IF NOT EXISTS pathway_id VARCHAR,
    ADD COLUMN IF NOT EXISTS procedure_id VARCHAR,
    ADD COLUMN IF NOT EXISTS procedure_type VARCHAR,
    ADD COLUMN IF NOT EXISTS procedure_date VARCHAR,
    ADD COLUMN IF NOT EXISTS modality VARCHAR,
    ADD COLUMN IF NOT EXISTS priority VARCHAR,
    ADD COLUMN IF NOT EXISTS ordered_date VARCHAR,
    ADD COLUMN IF NOT EXISTS scheduled_date VARCHAR,
    ADD COLUMN IF NOT EXISTS attendance_date VARCHAR,
    ADD COLUMN IF NOT EXISTS report_prepared_date VARCHAR,
    ADD COLUMN IF NOT EXISTS report_authorised_date VARCHAR,
    ADD COLUMN IF NOT EXISTS status VARCHAR,
    ADD COLUMN IF NOT EXISTS is_reported VARCHAR,
    ADD COLUMN IF NOT EXISTS source_system_name VARCHAR,
    ADD COLUMN IF NOT EXISTS last_refreshed_at_source_timestamp VARCHAR;

CREATE TABLE IF NOT EXISTS staging.pas_appointment (
    id SERIAL PRIMARY KEY,
    correlation_id VARCHAR,
    attendance_id VARCHAR,
    person_id VARCHAR,
    pathway_id VARCHAR,
    patient_nhs_number VARCHAR,
    mrn VARCHAR,
    appointment_type VARCHAR,
    booking_status VARCHAR,
    start_date_time VARCHAR,
    ordered_date VARCHAR,
    date_time_booked VARCHAR,
    source_system_name VARCHAR,
    last_refreshed_at_source_timestamp VARCHAR,
    processed_at TIMESTAMPTZ DEFAULT NOW(),
    mapping_status VARCHAR DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS staging.pas_encounter (
    id SERIAL PRIMARY KEY,
    correlation_id VARCHAR,
    encounter_id VARCHAR,
    person_id VARCHAR,
    pathway_id VARCHAR,
    patient_nhs_number VARCHAR,
    mrn VARCHAR,
    title VARCHAR,
    tci_status VARCHAR,
    surgical_order_date VARCHAR,
    admission_offer_timestamp VARCHAR,
    attendance_date VARCHAR,
    source_system_name VARCHAR,
    last_refreshed_at_source_timestamp VARCHAR,
    processed_at TIMESTAMPTZ DEFAULT NOW(),
    mapping_status VARCHAR DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS staging.ipt_source (
    id SERIAL PRIMARY KEY,
    correlation_id VARCHAR,
    tertiary_id VARCHAR,
    pathway_id VARCHAR,
    person_id VARCHAR,
    nhs_number VARCHAR,
    mrn VARCHAR,
    tertiary_referral_type VARCHAR,
    tertiary_reason VARCHAR,
    tertiary_reason_code VARCHAR,
    sending_org_id VARCHAR,
    sending_org_name VARCHAR,
    receiving_org_id VARCHAR,
    receiving_org_name VARCHAR,
    tertiary_sent_date VARCHAR,
    tertiary_received_date VARCHAR,
    tertiary_returned_date VARCHAR,
    tertiary_sending_comment VARCHAR,
    tertiary_return_comment VARCHAR,
    is_sent VARCHAR,
    is_received VARCHAR,
    is_returned VARCHAR,
    source_system_name VARCHAR,
    last_refreshed_at_source_timestamp VARCHAR,
    processed_at TIMESTAMPTZ DEFAULT NOW(),
    mapping_status VARCHAR DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS staging.comment_source (
    id SERIAL PRIMARY KEY,
    correlation_id VARCHAR,
    cancer_tracking_comment_id VARCHAR,
    cancer_pathway_id VARCHAR,
    person_id VARCHAR,
    nhs_number VARCHAR,
    mrn VARCHAR,
    comment_title VARCHAR,
    comment_text VARCHAR,
    created_by VARCHAR,
    created_at_timestamp VARCHAR,
    source_system_name VARCHAR,
    last_refreshed_at_source_timestamp VARCHAR,
    processed_at TIMESTAMPTZ DEFAULT NOW(),
    mapping_status VARCHAR DEFAULT 'pending'
);
