CREATE TABLE IF NOT EXISTS canonical.cancer_pathway (
    pathway_id VARCHAR PRIMARY KEY,
    person_id VARCHAR REFERENCES canonical.patient(person_id),
    mrn VARCHAR,
    nhs_number VARCHAR,
    first_name VARCHAR,
    surname VARCHAR,
    full_name VARCHAR,
    original_pathway_start_date DATE,
    pathway_closed_date DATE,
    waiting_time_adjustment_days INTEGER,
    adjusted_pathway_start_date DATE,
    cancer_site VARCHAR,
    cancer_sub_site VARCHAR,
    hospital_site VARCHAR,
    hospital_site_id VARCHAR REFERENCES ref.hospital_site(hospital_site_id),
    pathway_status VARCHAR,
    pathway_referral_route VARCHAR,
    first_seen_site VARCHAR,
    first_seen_site_ods_code VARCHAR,
    "28_day_breach_date" DATE,
    "31_day_breach_date" DATE,
    "62_day_breach_date" DATE,
    patient_informed_date DATE,
    referral_received_date DATE,
    upgrade_date DATE,
    date_of_birth DATE,
    date_of_death DATE,
    decision_to_treat_date DATE,
    diagnosis VARCHAR,
    diagnosis_icd_10_code VARCHAR,
    diagnosis_date DATE,
    first_seen_date DATE,
    first_treatment_date DATE,
    first_treatment_type VARCHAR,
    organisation_site_treatment VARCHAR,
    treatment_site_ods_code VARCHAR,
    treatment_site VARCHAR,
    referral_source VARCHAR,
    is_benign BOOLEAN,
    is_62_day_pathway_open BOOLEAN,
    is_31_day_pathway_open BOOLEAN,
    is_28_day_pathway_open BOOLEAN,
    is_any_pathway_type_open BOOLEAN,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    source_system_name VARCHAR,
    last_refreshed_at_source_timestamp TIMESTAMPTZ
);

COMMENT ON TABLE canonical.cancer_pathway IS 'Canonical cancer pathway record containing the operational PTL timeline, breach dates, diagnosis, and first treatment milestones.';
